### ISSUE TITLE
New Feature: Being able to extract files with Amsdos header from the DSK...

### ISSUE THREAD

**Issue by realmml** [damieng/DiskImageManager#2]
Hello Damien! :)

I am helping to the ScummVM people to improve the support of Amstrad CPC games using the freescape engine. Then I was explaining them, that the original disk versions of the freescape CPC games have not protection at all (maybe 2 or 3 packs), and because that it will be much better to use directly the files from the disks instead of implementing a .EDSK decoder in ScummVM. 

Then your DiskImageManager is perfect for that, because it is very easy to use, a lot easier than the usual old commandline tools (for example, they are not able to trim the files to the exact size, they use always a size multiple of the sector size, padding the end of the file with the usual $E5). 

But I can not find in DiskImageManager a way of extracting from the disk image the files with the Amsdos header. And I think that ScummVM should support cpc files with the original amsdos header; because between other things, we can put the same files in a disk image for using in the CPC and you don't need to know the details about loading address, execution address, ...

What do you think about this feature?

**Comment by damieng** [comment]
Hi there.

I am familiar with the ScummVM project having once contributed myself and used it many many times.

Yeah it's not just adding the EDSK reader itself it's then implementing file systems on top as EDSK just stores sectors and tracks. (and then with sidedness and interleave you have to jump around to find the right next logical sector not physical ones)

I have implemented two new menu options to allow files to be extracted with either PLUS3DOS or AMSDOS headers. I'll put up a new release now.

**Comment by damieng** [comment]
2.5.1 is up with this feature, let me know if it works for you.

**Comment by realmml** [comment]
Hi Damien! :)

I just tested and there is only a minor detail to fix, the file length in the Amsdos header doesn't count the 128 bytes of the header (you know, Amstrad, hehehe). Then when I extract a file is 128 bytes shorter, hehehe. 

Then add 128 to the amsdos header file lenght for extracting the full file and it will be perfect :)

Thank your for your fast answer Damien!!! :)

**Comment by damieng** [comment]
I've bumped the release (now build 106) which is available from the 2.5.1 release page which should include this fix.

**Comment by realmml** [comment]
Hi Damien! :)

I only have tested the last version now (2.5.1.106), and my problem is that when I try to extract any file with or without header, Disk Image Manager show me an Access Violation Error:
![error](https://user-images.githubusercontent.com/3588723/223228758-1806c2c2-a0a7-4bed-a76b-0257b44d5280.png)

And Disk Image Manager crash.

Or if it doesn't crash, the file will be created with length 0.

**Comment by damieng** [comment]
Sorry, rushing these out as I'm so busy elsewhere I know I wouldn't get to it for a week or two otherwise.

Try this one - I even tried it with the CastleMaster es CPC image.

https://github.com/damieng/DiskImageManager/releases/tag/2.5.1

**Comment by realmml** [comment]
Don't hurry up Damien! I can wait all the time that you need, it is not a problem at all.

Ok, Disk Image Manager doesn't crash anymore, but the files are 128 bytes shorter, as it happened in the previous version before the crash.

Let me explain well, because maybe I was not able to explain it before.

The Amsdos header are the first 128 bytes of every file. In this amsdos header, you can see the memory address where the data need to be loaded, the execution address in the case a binary file, a checksum, the file length without the header.

That means that the real file length is the one in the header (offset $18 and offset $19, as usual in z80 16 bits, lower byte before than upper byte) + 128 bytes (the header size).

Then when I extract a file with DIM, you are using only the file length in the header (offset $18 and $19), but you need to add 128 to that 16 bits value.
[Castle Master I (Spanish).zip](https://github.com/damieng/DiskImageManager/files/10903457/Castle.Master.I.Spanish.zip)

If you try to extract the CM.BIN file in the dsk that I have attached (Castle Master Spanish version), the file size should be 39.738 ($9B3A in hex in the header) + 128 = 39.866 bytes, but DIM is giving me a file of 39738 bytes.

Sorry, if I didn't explain me well, before.

**Comment by realmml** [comment]
Hi again! :)

I took a look to the code and the actual code at the end of the function TDSKFile.GetData() is:
```
// Strip any headers
  if (not WithHeader) and ((HeaderType = 'PLUS3DOS') or (HeaderType = 'AMSDOS')) then
    Result := Copy(FileData, HeaderSize, Size - HeaderSize)
  else
    Result := Copy(FileData, 0, Size);
end;

```
But it should be:
```
// Strip any headers
  if (not WithHeader) and ((HeaderType = 'PLUS3DOS') or (HeaderType = 'AMSDOS')) then
    Result := Copy(FileData, HeaderSize, Size)
  else
    Result := Copy(FileData, 0, Size + HeaderSize);
end;

```
When we don't want a header, we skip the header and get the size. But when we want the file with the header, then we want the full file, header included; then it should be Size (that you got in the header) + Header Size.

Related to my the previous message, I saw that you are using the 24 bits file size in the Amsdos header, that it is much better than using the 16 bits only. Great! :)

**Comment by damieng** [comment]
Yes, the code was assuming the Size included the header rather than excluded it - it has already been updated and a new version put out just a few minutes ago.

**Comment by damieng** [comment]
Is that build now working correctly for you?

**Comment by realmml** [comment]
YES! It is working perfectly :) :) :)

Sorry, I only was able to test it, now.

Thank you very much Damien :)
