### ISSUE TITLE
Amstrad CPC / BIN export from DSK / "Line too long"

### ISSUE THREAD

**Issue by ghost** [damieng/DiskImageManager#3]
Hi !

When I try to export a BIN program from a DSK file (option "Save BIN as") , I can't execute them on my Amstrad CPC 6128 with run command (message error : "Line too long") :(
Export work with other windows app like ManageDsk.
[SerialCpc.zip](https://github.com/damieng/DiskImageManager/files/10950114/SerialCpc.zip)

**Comment by damieng** [comment]
Can you try the latest build I just put out to see if that fixes it?

I just extracted `USIPLAYC.BIN` with it and both the header and non-header versions were identical to those produced by ManageDSK.

**Comment by ghost** [comment]
No Header  : doesn't work
With Header : Work ! :)

**Comment by damieng** [comment]
Ah, there you go! Glad it's working fine now.
